### PR TITLE
Remove Git ENV workflow

### PR DESCRIPTION
**Pull request by tahb**
- After our dev meeting we’ve decided to stop using both git flow and git env as philosophies
- I will add the new one in a separate PR as I forsee it requiring some debate before it can be merged in

### CODE REVIEW

**Comment by tomdxw** [comment]
@magdamaciaszczyk Why? What issues have you had with git env?

**Comment by magdamaciaszczyk** [comment]
@tomdxw since May I probably used it for a month or two and then I was told we don't deploy that way anymore. I'm merging everything using PR and it's working for me.

**Comment by tomdxw** [comment]
@magdamaciaszczyk It's correct that we use PRs to merge into `master`. The text which is being removed says that:

> all work for production should go through pull requests into the master branch, see [deploying](https://github.com/dxw/playbook/blob/master/guides/deploying.md) for more information.

**Comment by tahb** [comment]
There is another PR (https://github.com/dxw/playbook/pull/54) that's sorting out the `deploying.md` so I will remove the link in this PR.

**Comment by tahb** [comment]
Closed in favour of: https://github.com/dxw/playbook/pull/58

**Pull request closed without merging**
