### PR TITLE
Update Guides “card-sort”

### PR DESCRIPTION
**Pull request by Chanel-Diep**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by james** [comment]
Look good and sensible to me! Would you like me to merge these changes in now, or would you like someone else to check them first?

**Comment by Chanel-Diep** [comment]
Hello!

Up to you really!

Happy with the typo changes but only thing I would second guess is my
changing 'closed/open sort' to 'closed/open card sort' to make it more
consistent for the reader. Not sure if that goes against what's normal in
conversation?

I figured people new to it like me might prefer the clarity.

Thanks!

--
Chanel Diep
Content Designer
***@***.***
She/her
07710 470504

www.dxw.com :: 0345 257 7520 :: @dxw <https://twitter.com/dxw> :: creating
better digital public services

**Comment by Chanel-Diep** [comment]
...I'm assuming that was the long, waffly answer you were after? I guess
I'd say check just to be on the safe side please!

Thank you,
--
Chanel Diep
Content Designer
***@***.***
She/her
07710 470504

www.dxw.com :: 0345 257 7520 :: @dxw <https://twitter.com/dxw> :: creating
better digital public services

**Comment by james** [comment]
@Chanel-Diep Who would you like to check? Could you ask them?

**Comment by Chanel-Diep** [comment]
Will do, off sick today but will ask the Design team when I'm back in.
Thanks!
--
Chanel Diep
Content Designer
***@***.***
She/her
07710 470504

www.dxw.com :: 0345 257 7520 :: @dxw <https://twitter.com/dxw> :: creating
better digital public services

**Comment by Chanel-Diep** [comment]
Hi James,

TBC on those edits as we may be deleting the guide altogether it seems!

Thanks,
--
Chanel Diep
Content Designer
***@***.***
She/her
07710 470504

www.dxw.com :: 0345 257 7520 :: @dxw <https://twitter.com/dxw> :: creating
better digital public services

**Pull request closed without merging**
