### PR TITLE
Create Working here page “covid-and-in-person-working”

### PR DESCRIPTION
**Pull request by pgolden21**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by snim2** [comment]
This needs a bit of fixing because the numbers bullets from "At this time, and in line with ..." are all `1.`. 

Possibly removing the comments `<!---->` would do this?

**Comment by yndajas** [comment]
> This needs a bit of fixing because the numbers bullets from "At this time, and in line with ..." are all `1.`.
> 
> Possibly removing the comments `<!---->` would do this?

[This format](https://github.com/dxw/playbook/blob/main/src/user-research/card-sorting.md?plain=1#L39) should work: remove the spaces before the start of each new list item; indent the bullet points on item 2 with a few spaces (@pgolden21)

**Comment by yndajas** [comment]
> [This format](https://github.com/dxw/playbook/blob/main/src/user-research/card-sorting.md?plain=1#L39) should work: remove the spaces before the start of each new list item; indent the bullet points on item 2 with a few spaces (@pgolden21)
> 
> The quirks of Markdown 🫠

Looks like the list now restarts at 1 from the third item and continues going up from there - I think you'll need to do this ^ in the Markdown view to fix that

image

**Comment by yndajas** [comment]
Numbering and indentation looks good now, but I haven't reviewed the content so I'll leave approval to you if that's okay @snim2?

**Comment by snim2** [comment]
@yndajas thanks, I'll follow up after lunch!

**Review by snim2 — APPROVED** [review]

**Pull request merged**
