### PR TITLE
Updated "Who we are" text

### PR DESCRIPTION
**Pull request by duffylouise**
Doing this on Wendy's behalf - the Directors agreed on the new "who we are" text

### CODE REVIEW

**Comment by erbridge** [comment]
Louise, can you accept the GitHub invitation you were sent, please? https://github.com/dxw/playbook/invitations

**Comment by duffylouise** [comment]
I thought I did it the first time round but have just accepted it (I hope).

**Comment by erbridge** [comment]
You'll now want to make your changes again, sorry. What's happened is that GitHub helpfully created a fork for you, but the fork doesn't have the secrets set up that the test check needs. You'll need to use a branch in this repository instead, which I hope will happen automatically if you do another edit.

**Comment by erbridge** [comment]
Replaced by #398

**Pull request closed without merging**
