### PR TITLE
Move existing content into a Working here section

### PR DESCRIPTION
**Pull request by johnwaterworth**
Moved the internal focussed content into a Working here section with Managing your day to day work, Your pay, pension and other benefits, Supporting your development and wellbeing, and Hiring new people.
In future we can move the subsections into separate pages, and move more details material into guides where we can go into more detail.
For reviewers, my main concern is to check whether I've accidentally deleted anything.

### CODE REVIEW

**Comment by erbridge** [comment]
This PR lost aorund 40 lines of content. Was that expected?

**Comment by johnwaterworth** [comment]
There were two sections on the buddy system. I merged the two sections, removing the duplicated paragraphs and some out-of-date paragraphs that preceded line management and performance reviews.

**Comment by johnwaterworth** [comment]
I've checked the content in here against the current playbook and those are the only parts missing. I'll fix the conflicts.

Thanks for all your help with this.

**Comment by johnwaterworth** [comment]
Once this is merged, I will go through check the sections against an older version of the Playbook to make sure we've not lost anything. I think this is ready to merge now.

**Comment by lawrence-forooghian** [comment]
I’ve confirmed that the headings from the current playbook are either still there or have had their content moved elsewhere. I haven’t checked whether every single line of content is still there, because I’d still be here in a week 😃.

The only thing I noticed is that the sub-headings for "Returners' programme" have been accidentally bumped up a level. I’ll fix that, sort out the commits, and then I reckon we can merge this.

**Comment by johnwaterworth** [comment]
Thanks Lawrence. I'll do a detailed check against an older version of the Playbook once this is merged.

Shall I make you a reviewer so you can approve this request?

**Comment by lawrence-forooghian** [comment]
I don't think it's necessary – I think the reviewers thing exists more just to tell people that you'd like them to review it. Anyone in the company can review, actually.

**Pull request merged**
