### PR TITLE
Added that user research is about the best tasting salads

### PR DESCRIPTION
**Pull request by aitchchan**
In the northern hemisphere, specifically.

### CODE REVIEW

**Comment by Floppy** [comment]
This proposal is open for discussion and voting. If you are an [eligible voter](https://dxw-playbook-groupthink.herokuapp.com/users/) on this project (and not the proposer), you may cast your vote on whether or not it is accepted.

## How to vote
Vote by entering one of the following symbols in a comment on this pull request. Only your last vote will be counted, and you may change your vote at any time until the change is accepted or closed.

|vote|symbol|type this|points|
|--|--|--|--|
|Yes|:white_check_mark:|`:white_check_mark:`|1|
|No|:negative_squared_cross_mark:|`:negative_squared_cross_mark:`|-1|
|Abstain|:zipper_mouth_face:|`:zipper_mouth_face:`|0|
|Block|:no_entry_sign:|`:no_entry_sign:`|-10|

Proposals will be accepted and merged once they have a total of 2 points when all votes are counted. Votes will be open for a minimum of 1 days, but will be closed if the proposal is not accepted after 90.

Votes are counted [automatically here](https://dxw-playbook-groupthink.herokuapp.com/proposals/403), and results are set in the merge status checks below.

## Changes

@aitchchan, if you want to make further changes to this proposal, you can do so by [clicking on the pencil icons here](https://github.com/dxw/playbook/pull/403/files). If a change is made to the proposal, no votes cast before that change will be counted, and votes must be recast.

**Comment by erbridge** [comment]
Do we want all the voting stuff on this @Floppy?

**Comment by Floppy** [comment]
@erbridge no, we don't  - I need to disable that if the editor seems useful. Need to catch up with @aitchchan to see what she thought. I'll turn it all off for now to stop it spamming the place.

**Comment by erbridge** [comment]
Also, it sent me emails to my personal email address, even though this repo is set up to notify my dxw address.

**Comment by CristinaRO** [comment]
@aitchchan and @Floppy , I'll let you catch up about the experience of using the thing in your own time, but going to close this PR so it doesn't keep nagging us to review... (Also, 🍕 )

**Pull request closed without merging**
