### PR TITLE
Start on pivotal.md

### PR DESCRIPTION
**Pull request by tomdxw**

### CODE REVIEW

**Comment by tomdxw** [comment]
TODO: mention deployment notes

**Comment by harry-m** [comment]
@imagecircus @staceydxw @lexijax I think this is one for one of you to take ownership of and go through with the team?

Can someone volunteer?

**Comment by tahb** [comment]
I thought it was agreed that the current way of working wasn't working well. I drew up some notes for a new workflow based on lots of discussion had a few months ago: https://gist.github.com/tahb/f2a1e6d8d2083a46392c2fdcefff90f7

Is it just a case of having the dev meeting for process, choosing a new tool and writing it up more formally?

**Comment by imagecircus** [comment]
This will also be discussed in the next dev chat when Hippers is back next week.

**Comment by tahb** [comment]
Confident that this can be close now that we have migrated across to Trello.

**Pull request closed without merging**
